FLOATTYPE=float
PLATFORM=UNIX
CC=g++
CPP=g++	
INCLUDES=
CFLAGS=  -DFLOATTYPE=$(FLOATTYPE) -g -Wall -Wno-reorder -D$(PLATFORM)  -DDEBUG -std=c++11 -pedantic `sdl2-config --cflags` `xml2-config --cflags` $(LIBS)
LIBS= `sdl2-config --cflags --libs` `xml2-config --libs` -lSDL2_image -lSDL2_ttf -lboost_system -lboost_filesystem
#CFLAGS= -O3 -D$(PLATFORM) -DDEBUG
